FROM ruby:2.4-slim-jessie
LABEL maintainer="martin.stabenfeldt@shortcut.no"

RUN apt-get update
RUN apt-get install -y libpq-dev libgmp-dev libxml2-dev libxslt-dev
RUN apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev

COPY Gemfile* /app/
WORKDIR /app
RUN bundle install --jobs 20 --retry 5

