apiVersion: v1
kind: Service
metadata:
  name: colors-frontend
  labels:
    app: colors
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: colors
    tier: frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colors-frontend
  labels:
    app: colors
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: colors
        tier: frontend
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]


      - name: new-colors-app
        # Replace [YOUR_PROJECT_ID] with your project ID.
        image: docker.io/stabenfeldt/colors:latest
        imagePullPolicy: Always
        env:
          - name: FORMATION
            value: web=1
        ports:
        - name: http-server
          containerPort: 3000
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
