# Remember to update MY-INSTANCE

apiVersion: v1
kind: Service
metadata:
  name: colors-frontend
  labels:
    app: colors
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: colors
    tier: frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colors-frontend
  labels:
    app: colors
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: colors
        tier: frontend
    spec:
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=MY-INSTANCE:europe-west1:development=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
              - name: cloudsql-instance-credentials
                mountPath: /secrets/cloudsql
                readOnly: true


        - name: colors-app
          image: docker.io/stabenfeldt/colors:1
          imagePullPolicy: Always

          env:
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: RAILS_ENV
              value: development
            - name: POSTGRES_HOST
              value: 127.0.0.1
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password

          ports:
          - name: http-server
            containerPort: 3000
